server:
  port: 8103
  servlet:
    context-path: /api

spring:
  application:
    name: openApi-interface
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

api:
  gaode:
    key: 3eed07e21516dfd811a63c2d17e07827

dubbo:
  application:
    name: dubbo-springboot-demo-provider
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://localhost:8848